# Generated by Django 4.0.1 on 2022-01-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_appuser_carmodel_created_at_citymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='upload',
            field=models.FileField(default=1, upload_to='city_files/'),
            preserve_default=False,
        ),
    ]
